# Generated by Django 6.0.1 on 2026-01-23 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100)),
                ("message", models.CharField(max_length=500)),
                ("subject", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FEEDBACK", "Feedback"),
                            ("TESTIMONIAL", "Testimonial"),
                            ("BUG", "Bug Reponrt"),
                            ("FEATURE", "Feature Request"),
                            ("SUPPORT", "Support"),
                        ],
                        default="FEEDBACK",
                        max_length=20,
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("USER", "User"), ("STAFF", "staff")],
                        default="STAFF",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "new"),
                            ("REPLIED", "Replied"),
                            ("ONGOING", "On Going"),
                            ("CLOSED", "Closed"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                ("is_pulic", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="customer_service.customermessage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Customer Service",
            },
        ),
    ]
