# Generated by Django 6.0.1 on 2026-01-23 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customermessage",
            name="email",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
