# Generated by Django 6.0.1 on 2026-01-23 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_service", "0002_customermessage_email"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customermessage",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Customer Message",
                "verbose_name_plural": "Customer Messages",
            },
        ),
        migrations.RenameField(
            model_name="customermessage",
            old_name="is_pulic",
            new_name="is_public",
        ),
        migrations.RemoveField(
            model_name="customermessage",
            name="email",
        ),
        migrations.RemoveField(
            model_name="customermessage",
            name="name",
        ),
        migrations.AddField(
            model_name="customermessage",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customermessage",
            name="category",
            field=models.CharField(
                choices=[
                    ("FEEDBACK", "Feedback"),
                    ("TESTIMONIAL", "Testimonial"),
                    ("BUG", "Bug Report"),
                    ("FEATURE", "Feature Request"),
                    ("SUPPORT", "Support"),
                ],
                default="FEEDBACK",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customermessage",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="customermessage",
            name="sender",
            field=models.CharField(
                choices=[("USER", "User"), ("STAFF", "Staff")],
                default="USER",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customermessage",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("REPLIED", "Replied"),
                    ("ONGOING", "On Going"),
                    ("CLOSED", "Closed"),
                ],
                default="NEW",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customermessage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer_messages",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
