# Generated by Django 6.0.1 on 2026-02-23 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_alter_customermessage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReachout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('project_topic', models.CharField(blank=True, choices=[('urban_gis', 'Urban GIS Dashboard'), ('field_team', 'Field Team Offline System'), ('spatial_analysis', 'Spatial Analytics'), ('other', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
        ),
    ]
