# Generated by Django 6.0.1 on 2026-01-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_bio_remove_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=50, help_text='Maximum allowed storage for this user in MB'),
        ),
        migrations.AddField(
            model_name='profile',
            name='used_storage_mb',
            field=models.FloatField(default=0.0, help_text='Storage used by the user in MB'),
        ),
    ]
