# Generated by Django 6.0.1 on 2026-01-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_storage_limit_mb_profile_used_storage_mb'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
