# Generated by Django 6.0.1 on 2026-01-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='used_storage_mb',
        ),
    ]
