# Generated by Django 6.0.1 on 2026-01-27 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_profile_used_storage_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=10, help_text='Maximum allowed storage for this user in MB'),
        ),
    ]
