# Generated by Django 6.0.1 on 2026-01-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_storage_limit_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='storage_limit_mb',
            field=models.PositiveIntegerField(default=50, help_text='Maximum allowed storage for this user in MB'),
        ),
    ]
