# Generated by Django 6.0.1 on 2026-01-22 20:03

import django.db.models.deletion
import gis_database.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("archived", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                ("to_trash", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created this project",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=gis_database.models.user_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="gis_database.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=gis_database.models.user_upload_path),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced", models.BooleanField(default=False)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "remote_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="gis_database.projectfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "indexes": [
                    models.Index(
                        fields=["synced"], name="gis_databas_synced_f71b14_idx"
                    )
                ],
                "unique_together": {("project_file", "version_number")},
            },
        ),
    ]
