# Generated by Django 6.0.1 on 2026-01-31 18:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0002_remove_file_one_latest_file_per_logical_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('owner', 'name')},
        ),
    ]
