# Generated by Django 6.0.1 on 2026-01-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_database", "0002_project_delete_myfile"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
            },
        ),
        migrations.AddField(
            model_name="project",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
