# Generated by Django 6.0.1 on 2026-01-20 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_database", "0003_alter_project_options_project_archived_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owner",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
