# Generated by Django 6.0.1 on 2026-02-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0004_projectmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileactivity',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_database.file'),
        ),
    ]
