# Generated by Django 6.0.1 on 2026-01-20 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_database", "0004_project_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="user",
            field=models.ForeignKey(
                help_text="The user who created this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
