# Generated by Django 6.0.1 on 2026-02-19 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0005_alter_fileactivity_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileactivity',
            name='file_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
