# Generated by Django 6.0.1 on 2026-01-21 08:09

import django.db.models.deletion
import gis_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_database", "0005_alter_project_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=gis_database.models.user_upload_path
            ),
        ),
        migrations.CreateModel(
            name="ProjectVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=gis_database.models.user_upload_path),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="gis_database.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("project", "version_number")},
            },
        ),
    ]
