# Generated by Django 6.0.1 on 2026-01-22 04:25

import django.db.models.deletion
import gis_database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gis_database", "0006_alter_project_file_projectversion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="file",
        ),
        migrations.AddField(
            model_name="project",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="to_trash",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="ProjectFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=gis_database.models.user_upload_path),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="gis_database.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectFileVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to=gis_database.models.user_upload_path),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("synced", models.BooleanField(default=False)),
                ("checksum", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "remote_path",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="gis_database.projectfile",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
            },
        ),
        migrations.DeleteModel(
            name="ProjectVersion",
        ),
        migrations.AddIndex(
            model_name="projectfileversion",
            index=models.Index(fields=["synced"], name="gis_databas_synced_f71b14_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="projectfileversion",
            unique_together={("project_file", "version_number")},
        ),
    ]
