# Generated by Django 6.0.1 on 2026-02-19 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0006_fileactivity_file_name_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileactivity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gis_database.project'),
        ),
        migrations.AddField(
            model_name='fileactivity',
            name='project_name_snapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
