# Generated by Django 6.0.1 on 2026-02-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0007_fileactivity_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VectorFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
