# Generated by Django 6.0.1 on 2026-02-20 06:22

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_database', '0009_geofeature_delete_vectorfiles_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpatialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(srid=4326)),
                ('properties', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='geofeature',
            name='gis_databas_geometr_c66e6e_idx',
        ),
        migrations.AddField(
            model_name='spatialdata',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_database.project'),
        ),
        migrations.AddField(
            model_name='spatialdata',
            name='source_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gis_database.file'),
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='project',
        ),
        migrations.RemoveField(
            model_name='geofeature',
            name='source_file',
        ),
        migrations.AddIndex(
            model_name='spatialdata',
            index=models.Index(fields=['geometry'], name='gis_databas_geometr_b19c79_idx'),
        ),
        migrations.DeleteModel(
            name='GeoFeature',
        ),
    ]
