services:
  db:
    image: postgis/postgis:16-3.5-alpine
    container_name: postgis_db
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    shm_size: 256mb
    networks:
      - gis_centralize_db

networks:
  gis_centralize_db:
    external: true